#!/usr/bin/env python3
import os
import json
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    accuracy_score,
)
from sklearn.ensemble import RandomForestClassifier

# -------------------------------
# Config
# -------------------------------
WINDOWS = [1, 2, 5, 10, 20, 30, 50, 60]

# Folder with early_{t}s.csv generated by build_time_aware_datasets_THC_rich_v1.py
DATA_DIR = "out_early_windows_THC_rich_enriched"

# Where to save results
OUT_DIR = "rf_results_time_windows"

RANDOM_STATE = 42

# -------------------------------
# Feature selection
# -------------------------------
# Numeric features (from your rich dataset)
NUMERIC_FEATURES = [
    "current_a",
    "voltage_v",
    "power_w",
    "capacity_ah",
    "spec_cap",
    "chg_cap",
    "chg_spec",
    "dchg_cap",
    "dchg_spec",
    "energy_wh",
    "t_cum_s",
    "dvdt_v_per_s",
]

# Categorical features (optional)
# step_type is often noisy; mission_step can help (takeoff/hover/cruise)
CATEGORICAL_FEATURES = [
    "mission_step",
    # "step_type",  # enable only if you want
]

LABEL_COL = "label"

# -------------------------------
# Utilities
# -------------------------------

def load_window_df(window_s: int) -> pd.DataFrame:
    path = os.path.join(DATA_DIR, f"early_{window_s}s_enriched.csv")
    df = pd.read_csv(path)

    # Basic cleanup
    # Keep only needed columns if present
    keep_cols = ["file", "Cycle", LABEL_COL] + NUMERIC_FEATURES + CATEGORICAL_FEATURES
    keep_cols = [c for c in keep_cols if c in df.columns]
    df = df[keep_cols].copy()

    df[LABEL_COL] = df[LABEL_COL].astype(str)

    # Remove obviously invalid rows (optional)
    # Example: drop rows with missing label
    df = df.dropna(subset=[LABEL_COL])

    return df

def add_cycle_relative_features(df):
    df = df.copy()

    # sort to ensure correct first sample
    df = df.sort_values(["file", "Cycle", "t_cum_s"])

    # compute per-cycle baseline
    first_rows = (
        df.groupby(["file", "Cycle"])
        .first()
        .reset_index()[["file", "Cycle",
                        "voltage_v",
                        "capacity_ah",
                        "energy_wh",
                        "power_w"]]
        .rename(columns={
            "voltage_v": "V0",
            "capacity_ah": "Cap0",
            "energy_wh": "E0",
            "power_w": "P0"
        })
    )

    df = df.merge(first_rows, on=["file", "Cycle"], how="left")

    # delta features
    df["voltage_delta"] = df["voltage_v"] - df["V0"]
    df["capacity_delta"] = df["capacity_ah"] - df["Cap0"]
    df["energy_delta"] = df["energy_wh"] - df["E0"]
    df["power_delta"] = df["power_w"] - df["P0"]

    # ratio features (safe division)
    df["voltage_ratio"] = df["voltage_v"] / (df["V0"] + 1e-6)
    df["energy_ratio"] = df["energy_wh"] / (df["E0"] + 1e-6)

    return df



def stratified_file_split(df_ref: pd.DataFrame, test_size=0.30, random_state=42):
    """
    Split by file, stratified by each file's dominant class.
    Use a reference df (ideally 60s) so split is consistent across windows.
    """
    file_counts = (
        df_ref.groupby("file")[LABEL_COL]
        .value_counts()
        .unstack(fill_value=0)
    )
    file_counts["dominant_class"] = file_counts.idxmax(axis=1)
    file_info = file_counts.reset_index()[["file", "dominant_class"]]

    train_files, test_files = train_test_split(
        file_info["file"].values,
        test_size=test_size,
        random_state=random_state,
        stratify=file_info["dominant_class"].values
    )
    return set(train_files), set(test_files), file_counts


def build_model(numeric_features, categorical_features):
    numeric_transformer = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
        ]
    )

    categorical_transformer = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot", OneHotEncoder(handle_unknown="ignore")),
        ]
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, numeric_features),
            ("cat", categorical_transformer, categorical_features),
        ],
        remainder="drop",
        verbose_feature_names_out=False,
    )

    rf = RandomForestClassifier(
        n_estimators=500,
        random_state=RANDOM_STATE,
        n_jobs=-1,
        class_weight="balanced",
        max_depth=None,
        min_samples_leaf=1,
    )

    model = Pipeline(
        steps=[
            ("prep", preprocessor),
            ("rf", rf),
        ]
    )
    return model


def cycle_level_metrics(df_test: pd.DataFrame, proba: np.ndarray, classes: np.ndarray):
    """
    Convert datapoint predictions -> cycle predictions by averaging probabilities
    per (file, Cycle).
    """
    tmp = df_test[["file", "Cycle", LABEL_COL]].copy()
    for i, c in enumerate(classes):
        tmp[f"p_{c}"] = proba[:, i]

    grp = tmp.groupby(["file", "Cycle"], as_index=False)
    prob_cols = [f"p_{c}" for c in classes]
    cy = grp[prob_cols].mean()

    # true label per cycle (first)
    y_true_cycle = grp[LABEL_COL].first()[LABEL_COL].values
    y_pred_cycle = classes[np.argmax(cy[prob_cols].values, axis=1)]

    return {
        "cycle_accuracy": float(accuracy_score(y_true_cycle, y_pred_cycle)),
        "cycle_macro_f1": float(f1_score(y_true_cycle, y_pred_cycle, average="macro")),
        "cycle_cm": confusion_matrix(y_true_cycle, y_pred_cycle, labels=classes).tolist(),
    }

import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix

def cycle_fuse_predictions(df_test, proba, classes, method="mean"):
    tmp = df_test[["file","Cycle","label"]].copy()
    for i, c in enumerate(classes):
        tmp[f"p_{c}"] = proba[:, i]

    prob_cols = [f"p_{c}" for c in classes]

    if method == "mean":
        agg = tmp.groupby(["file","Cycle"], as_index=False)[prob_cols].mean()
    elif method == "logsum":
        # sum log-probabilities across datapoints (more robust than mean)
        eps = 1e-9
        tmp_log = tmp.copy()
        for col in prob_cols:
            tmp_log[col] = np.log(tmp_log[col] + eps)
        agg = tmp_log.groupby(["file","Cycle"], as_index=False)[prob_cols].sum()
    else:
        raise ValueError("method must be 'mean' or 'logsum'")

    # true label per cycle
    y_true = tmp.groupby(["file","Cycle"])["label"].first().values
    y_pred = classes[np.argmax(agg[prob_cols].values, axis=1)]

    return {
        "cycle_acc": float(accuracy_score(y_true, y_pred)),
        "cycle_macro_f1": float(f1_score(y_true, y_pred, average="macro")),
        "cycle_cm": confusion_matrix(y_true, y_pred, labels=classes),
    }

def cycle_fuse_predictions_topk(df_test, proba, classes, k=25, score_by="min_voltage", method="logsum"):
    """
    Fuse datapoint predictions into cycle prediction using only top-k informative datapoints per cycle.

    score_by:
      - "min_voltage": pick k lowest voltage_v points per (file,Cycle)
      - "max_abs_dvdt": pick k largest |dvdt_v_per_s| points per (file,Cycle)
      - "first_k": pick first k points by t_cum_s
    method:
      - "logsum" recommended
      - "mean" supported
    """
    tmp = df_test[["file", "Cycle", "label", "t_cum_s", "voltage_v", "dvdt_v_per_s"]].copy()

    for i, c in enumerate(classes):
        tmp[f"p_{c}"] = proba[:, i]

    prob_cols = [f"p_{c}" for c in classes]

    # choose top-k rows per cycle
    def pick_group(g):
        if score_by == "min_voltage":
            g2 = g.sort_values("voltage_v", ascending=True)
        elif score_by == "max_abs_dvdt":
            g2 = g.assign(_s=np.abs(g["dvdt_v_per_s"])).sort_values("_s", ascending=False)
        elif score_by == "first_k":
            g2 = g.sort_values("t_cum_s", ascending=True)
        else:
            raise ValueError("score_by must be one of: min_voltage, max_abs_dvdt, first_k")
        return g2.head(k)

    tmp = tmp.groupby(["file", "Cycle"], group_keys=False).apply(pick_group)

    if method == "mean":
        agg = tmp.groupby(["file", "Cycle"], as_index=False)[prob_cols].mean()
    elif method == "logsum":
        eps = 1e-9
        tmp_log = tmp.copy()
        for col in prob_cols:
            tmp_log[col] = np.log(tmp_log[col] + eps)
        agg = tmp_log.groupby(["file", "Cycle"], as_index=False)[prob_cols].sum()
    else:
        raise ValueError("method must be 'mean' or 'logsum'")

    y_true = tmp.groupby(["file", "Cycle"])["label"].first().values
    y_pred = classes[np.argmax(agg[prob_cols].values, axis=1)]

    return {
        "cycle_acc": float(accuracy_score(y_true, y_pred)),
        "cycle_macro_f1": float(f1_score(y_true, y_pred, average="macro")),
        "cycle_cm": confusion_matrix(y_true, y_pred, labels=classes),
    }


# -------------------------------
# Main training loop
# -------------------------------

def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    # # df = pd.read_csv("out_early_windows_THC_rich_enriched/early_10s_enriched.csv")
    # # print(df.columns)
    # # print(len(df))
    #
    # df = pd.read_csv("out_early_windows_THC_rich_enriched/early_60s_enriched.csv")
    #
    # print(df.groupby("label")["Vsag_upto"].mean())
    # print(df.groupby("label")["dVdt_slope_upto"].mean())
    # print(df.groupby("label")["Cap_delta"].mean())
    # print(df.groupby("label")["I_abs_mean_upto"].mean())
    #
    # for col in ["Vsag_upto", "dVdt_slope_upto", "Cap_delta", "I_abs_mean_upto"]:
    #     print("\n", col)
    #     print(df.groupby("label")[col].describe())
    #
    # exit(1)

    # Use 60s as reference for stable file split
    df_ref = load_window_df(60)

    train_files, test_files, file_counts = stratified_file_split(df_ref, test_size=0.30, random_state=RANDOM_STATE)

    # Save file split
    pd.DataFrame({"train_files": sorted(list(train_files))}).to_csv(os.path.join(OUT_DIR, "train_files.csv"), index=False)
    pd.DataFrame({"test_files": sorted(list(test_files))}).to_csv(os.path.join(OUT_DIR, "test_files.csv"), index=False)
    file_counts.reset_index().to_csv(os.path.join(OUT_DIR, "file_label_counts_ref60s.csv"), index=False)

    results = []

    for w in WINDOWS:
        df = load_window_df(w)
        # df = add_cycle_relative_features(df)

        train_df = df[df["file"].isin(train_files)].copy()
        test_df  = df[df["file"].isin(test_files)].copy()

        # If a window has very few rows in test/train, you’ll see it here
        print(f"\n=== Window {w}s ===")
        print("Train rows:", len(train_df), " Test rows:", len(test_df))

        # Define X/y
        X_train = train_df[[c for c in NUMERIC_FEATURES + CATEGORICAL_FEATURES if c in train_df.columns]]
        y_train = train_df[LABEL_COL].astype(str).values

        X_test = test_df[[c for c in NUMERIC_FEATURES + CATEGORICAL_FEATURES if c in test_df.columns]]
        y_test = test_df[LABEL_COL].astype(str).values

        # Build + train
        model = build_model(
            numeric_features=[c for c in NUMERIC_FEATURES if c in X_train.columns],
            categorical_features=[c for c in CATEGORICAL_FEATURES if c in X_train.columns],
        )

        model.fit(X_train, y_train)

        # Predict
        y_pred = model.predict(X_test)
        proba = model.predict_proba(X_test)
        classes = model.named_steps["rf"].classes_

        # cy = cycle_fuse_predictions(test_df, proba, classes, method="logsum")
        cy = cycle_fuse_predictions_topk(
            test_df, proba, classes,
            k=25,  # try 10, 25, 50
            score_by="min_voltage",  # best for sag/collapse
            method="logsum"
        )

        cycle_acc = cy["cycle_acc"]
        cycle_f1 = cy["cycle_macro_f1"]

        print(cy["cycle_acc"], cy["cycle_macro_f1"])

        cy2 = cycle_fuse_predictions_topk(test_df, proba, classes, k=25, score_by="max_abs_dvdt", method="logsum")
        print("Cycle topk(minV) acc/f1:", cy["cycle_acc"], cy["cycle_macro_f1"])
        print("Cycle topk(|dVdt|) acc/f1:", cy2["cycle_acc"], cy2["cycle_macro_f1"])

        # Metrics (datapoint-level)
        acc = float(accuracy_score(y_test, y_pred))
        macro_f1 = float(f1_score(y_test, y_pred, average="macro"))
        cm = confusion_matrix(y_test, y_pred, labels=classes)

        # Save per-window reports
        rep = classification_report(y_test, y_pred, labels=classes, output_dict=True, zero_division=0)

        # Cycle-level aggregation metrics
        cy_metrics = cycle_level_metrics(test_df, proba, classes)

        # Store summary
        row = {
            "window_s": w,
            "train_rows": int(len(train_df)),
            "test_rows": int(len(test_df)),
            "datapoint_accuracy": acc,
            "datapoint_macro_f1": macro_f1,
            "cycle_accuracy": cy_metrics["cycle_accuracy"],
            "cycle_macro_f1": cy_metrics["cycle_macro_f1"],
        }
        results.append(row)

        # Write artifacts
        out_prefix = os.path.join(OUT_DIR, f"rf_window_{w}s")

        pd.DataFrame(cm, index=[f"true_{c}" for c in classes], columns=[f"pred_{c}" for c in classes]) \
          .to_csv(out_prefix + "_cm_datapoint.csv")

        pd.DataFrame(cy_metrics["cycle_cm"], index=[f"true_{c}" for c in classes], columns=[f"pred_{c}" for c in classes]) \
          .to_csv(out_prefix + "_cm_cycle.csv")

        with open(out_prefix + "_report.json", "w") as f:
            json.dump(rep, f, indent=2)

        # Save model if you want (optional; can get large)
        # import joblib
        # joblib.dump(model, out_prefix + "_model.joblib")

        print("Datapoint macro-F1:", macro_f1, " Cycle macro-F1:", cy_metrics["cycle_macro_f1"])

    # Final summary
    res_df = pd.DataFrame(results).sort_values("window_s")
    res_df.to_csv(os.path.join(OUT_DIR, "rf_all_windows_summary.csv"), index=False)
    print("\n[DONE] Wrote:", os.path.join(OUT_DIR, "rf_all_windows_summary.csv"))
    print(res_df)

if __name__ == "__main__":
    main()
